package GUI.add;

import BUS.CTKMTheoHdBUS;
import BUS.KhuyenMaiBUS;
import DTO.ChiTietKMTheoHDDTO;
import DTO.KhuyenMaiDTO;
import DTO.Session;
import GUI.KhuyenMai;
import helper.Validation;
import java.awt.Window;
import java.util.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class addKMTheoHoaDon extends javax.swing.JDialog {
      KhuyenMaiBUS kmBus = new KhuyenMaiBUS();
      CTKMTheoHdBUS ctkmBus = new CTKMTheoHdBUS();
      private Boolean addSuccess = false;
      private Validation v = new Validation();

      /**
       * Creates new form addKMTheoHoaDon
       */
      public addKMTheoHoaDon(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            setModal(modal);
            initComponents();
            setLocationRelativeTo(null);
      }

      public addKMTheoHoaDon() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      }

      public addKMTheoHoaDon(KhuyenMai aThis, Window windowAncestor, boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      }

      public boolean isAddedSuccessfully() {
            return addSuccess;
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            ngayKThuc = new com.toedter.calendar.JDateChooser();
            ngayBdau = new com.toedter.calendar.JDateChooser();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            txtTenCTKM = new javax.swing.JTextField();
            txtPhanTramGiam = new javax.swing.JTextField();
            btnThem = new javax.swing.JButton();
            jLabel6 = new javax.swing.JLabel();
            txtĐKHoaDon = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(0, 153, 204));

            jLabel1.setBackground(new java.awt.Color(51, 153, 255));
            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("KHUYẾN MÃI THEO HÓA ĐƠN");
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
            );

            jLabel2.setText("Tên chương trình  khuyến mãi");

            jLabel3.setText("Phần trăm giảm");

            ngayKThuc.setDateFormatString("yyyy-MM-dd");

            ngayBdau.setDateFormatString("yyyy-MM-dd");

            jLabel4.setText("Ngày bắt đầu :");

            jLabel5.setText("Ngày kết thúc :");

            txtTenCTKM.setHorizontalAlignment(javax.swing.JTextField.LEFT);

            txtPhanTramGiam.setHorizontalAlignment(javax.swing.JTextField.LEFT);

            btnThem.setBackground(new java.awt.Color(51, 204, 0));
            btnThem.setText("THÊM KHUYẾN MÃI");
            btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnThem.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnThemActionPerformed(evt);
                  }
            });

            jLabel6.setText("Điều kiện hóa đơn");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(ngayBdau, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(ngayKThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtĐKHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addComponent(txtTenCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(btnThem)))
                        .addContainerGap(65, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel6)
                              .addComponent(txtĐKHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(ngayKThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(ngayBdau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
          String message = "";
          if (txtTenCTKM.getText().isEmpty()) {
                message = " Tên chương trình khuyến mãi không được để trống!";
          } else if (txtPhanTramGiam.getText().isEmpty()) {
                message = "Phần trăm khuyến mãi không được để trống!";
          } else if (txtĐKHoaDon.getText().isEmpty()) {
                message = "Điều kiện hóa đơn không được để trống!";
          } else if (ngayBdau.getDate() == null) {
                message = "Vui lòng chọn ngày bắt đầu!";
          } else if (ngayKThuc.getDate() == null) {
                message = "Vui lòng chọn ngày kết thúc!";
          } else if (kmBus.kmDAO.isOverLapKMHD(new java.sql.Date(ngayBdau.getDate().getTime()), new java.sql.Date(ngayKThuc.getDate().getTime()))) {
                JOptionPane.showMessageDialog(null, "Thời gian khuyến mãi không được trùng lặp với các chương trình đã tạo trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
          } else {
                try {
                      float dkhd = Float.parseFloat(txtĐKHoaDon.getText());
                      String tenCTKM = txtTenCTKM.getText();
                      Date ngayBD = ngayBdau.getDate();
                      Date ngayKT = ngayKThuc.getDate();
                      int phanTramGiam = Integer.parseInt(txtPhanTramGiam.getText());

                      if (!ctkmBus.checkGiaDKHD(dkhd)) {
                            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá điều kiện từ 1 đến 999999");
                            return;
                      } else if (!v.isValidName(tenCTKM)) {
                            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên chương trình khuyến mãi từ 6 đến 30 kí tự");
                            return;
                      } else if (!ctkmBus.checkPhanTramGiam(phanTramGiam)) {
                            JOptionPane.showMessageDialog(this, "Vui lòng nhập phần trăm giảm từ 1 đến 100");
                            return;
                      } else {
                            KhuyenMaiDTO kmDTO = new KhuyenMaiDTO();
                            kmDTO.setLoaiKM("Theo hóa đơn");
                            kmDTO.setTgBatDau(ngayBD);
                            kmDTO.setTgKetThuc(ngayKT);

                            ChiTietKMTheoHDDTO ctkmDTO = new ChiTietKMTheoHDDTO();
                            int makm = kmBus.kmDAO.getAutoIncrement();
                            System.out.println("Mã khuyến mãi" + makm);
                            ctkmDTO.setMaKM(makm);
                            ctkmDTO.setTenCTKM(tenCTKM);
                            System.out.println("Chương trình khuyến mãi" + ctkmDTO.getTenCTKM());
                            ctkmDTO.setTgBatDau(ngayBD);
                            ctkmDTO.setTgKetThuc(ngayKT);
                            System.out.println(Session.getNv().getHoten());
                            ctkmDTO.setNvTao(Session.getNv().getHoten());
                            System.out.println("Tên nhân viên tạo" + ctkmDTO.getNvTao());
                            ctkmDTO.setPhanTramGiam(phanTramGiam);
                            ctkmDTO.setDkHoaDon(dkhd);

                            if (kmBus.insert(kmDTO)) {
                                  if (ctkmBus.insert(ctkmDTO)) {
                                        addSuccess = true;
                                        JOptionPane.showMessageDialog(null, "Tạo thành công khuyến mãi theo hóa đơn!");
                                        this.dispose();
                                  
                                  }
                            }
                      }
                } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng!");
                }
          }
          if (!message.isEmpty()) {
                JOptionPane.showMessageDialog(null, message, "Thông báo", JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_btnThemActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(addKMTheoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(addKMTheoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(addKMTheoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(addKMTheoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        addKMTheoHoaDon dialog = new addKMTheoHoaDon(new javax.swing.JFrame(), true);
                        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                              @Override
                              public void windowClosing(java.awt.event.WindowEvent e) {
                                    System.exit(0);
                              }
                        });
                        dialog.setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnThem;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JPanel jPanel1;
      private com.toedter.calendar.JDateChooser ngayBdau;
      private com.toedter.calendar.JDateChooser ngayKThuc;
      private javax.swing.JTextField txtPhanTramGiam;
      private javax.swing.JTextField txtTenCTKM;
      private javax.swing.JTextField txtĐKHoaDon;
      // End of variables declaration//GEN-END:variables
}
