/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.add;

import Controler.SearchSanPham;
import BUS.CTKMTheoHdBUS;
import BUS.CTKMTheoSpBUS;
import BUS.SanPhamBUS;
import DTO.SanPhamDTO;
import BUS.PhieuXuatBUS;
import DTO.PhieuXuatDTO;
import BUS.GiamGiaBUS;
import BUS.KhachHangBUS;
import BUS.KhuyenMaiBUS;
import BUS.LoHangBUS;
import DTO.KhachHangDTO;
import BUS.NhanVienBUS;
import DTO.ChiTietKMTheoHDDTO;
import DTO.ChiTietKMTheoSPDTO;
import DTO.ChiTietPhieuXuatDTO;
import DTO.KhuyenMaiDTO;
import DTO.LoHangDTO;
import DTO.NhanVienDTO;
import GUI.login;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NeON
 */
public class addphieuxuat extends javax.swing.JPanel {

    ArrayList<SanPhamDTO> list = new ArrayList<SanPhamDTO>();
    ArrayList<NhanVienDTO> listTennv = new ArrayList<NhanVienDTO>();
    SanPhamBUS spBUS = new SanPhamBUS();
    PhieuXuatBUS pxBUS = new PhieuXuatBUS();
    GiamGiaBUS ggBUS = new GiamGiaBUS();
    KhachHangBUS khBUS = new KhachHangBUS();
    NhanVienBUS nvBUS = new NhanVienBUS();
    LoHangBUS lhBUS = new LoHangBUS();
    KhuyenMaiBUS kmBUS = new KhuyenMaiBUS();
    CTKMTheoHdBUS ctkmHDBus = new CTKMTheoHdBUS();
    int current = 0;

    public addphieuxuat() {
        initComponents();

        combohotenDisplay();
        cbxAllDisplay();
        listTennv = nvBUS.nvDAO.selectAll();
        displaytoTxttennvxuat(listTennv);
        list = spBUS.spDAO.selectAll();
        txtMaKM.setEditable(false);
        for (SanPhamDTO sp : list) {
            setGiaKhuyenMai(sp);
        }
        displaytoTable1(list);

        txtsdt.setEditable(false);
        txtdiachi.setEditable(false);
        txttennvxuat.setEditable(false);
        tblphieuxuatin.setDefaultEditor(Object.class, null);
        tblphieuxuatout.setDefaultEditor(Object.class, null);
    }

    public void setGiaKhuyenMai(SanPhamDTO sp) {
        CTKMTheoSpBUS ctkmBus = new CTKMTheoSpBUS();
        ArrayList<ChiTietKMTheoSPDTO> listctkm = ctkmBus.getAll();
        Date now = new Date();
        int giaKM = sp.getGiaban();

        for (ChiTietKMTheoSPDTO ctkm : listctkm) {
            if (!ctkm.getTgKetThuc().before(now) && ctkm.getMaSP() == sp.getMasp()) {
                int phanTramGiam = ctkm.getPhanTramGiam();
                giaKM = sp.getGiaban() - (sp.getGiaban() * phanTramGiam / 100);
                break;
            }
        }
        sp.setGiaKM(giaKM);
    }

    private void displaytoTable1(ArrayList<SanPhamDTO> list) {
        try {
            DefaultTableModel dt = (DefaultTableModel) tblphieuxuatin.getModel();
            dt.setRowCount(0);
            for (SanPhamDTO i : list) {
                if (i.getSoluongton() >= 1) {
                    dt.addRow(new Object[]{
                        i.getMasp(), i.getTensp(), i.getSoluongton(), i.getGiaban()
                    });
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void cbxAllDisplay() {
        cbxAll.addItem("Tất cả");
        cbxAll.addItem("Mã sản phẩm");
        cbxAll.addItem("Tên sản phẩm");
    }

    private void combohotenDisplay() {
        ArrayList<KhachHangDTO> listkh = khBUS.khDAO.selectAll();
        for (KhachHangDTO kh : listkh) {
            combohoten.addItem(kh.getHoten());
        }
    }

    private void displaytoTxttennvxuat(ArrayList<NhanVienDTO> listTennv) {
        for (NhanVienDTO j : listTennv) {
            if (login.t.getMaaccount() == j.getManv()) {
                txttennvxuat.setText("" + j.getHoten());
                break;
            }
        }
    }

    /**
     * fo This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            groupGioiTinh = new javax.swing.ButtonGroup();
            jPanel1 = new javax.swing.JPanel();
            jScrollPane2 = new javax.swing.JScrollPane();
            tblphieuxuatin = new javax.swing.JTable();
            btnthemsp = new javax.swing.JButton();
            jLabel12 = new javax.swing.JLabel();
            txtsoluong = new javax.swing.JTextField();
            jLabel17 = new javax.swing.JLabel();
            txttennvxuat = new javax.swing.JTextField();
            cbxAll = new javax.swing.JComboBox<>();
            jLabel16 = new javax.swing.JLabel();
            jLabel18 = new javax.swing.JLabel();
            txttimkiemsp = new javax.swing.JTextField();
            jPanel6 = new javax.swing.JPanel();
            btnxuatphieu = new javax.swing.JButton();
            jLabel13 = new javax.swing.JLabel();
            txtsdt = new javax.swing.JTextField();
            jLabel14 = new javax.swing.JLabel();
            txtdiachi = new javax.swing.JTextField();
            jLabel15 = new javax.swing.JLabel();
            combohoten = new javax.swing.JComboBox<>();
            jScrollPane3 = new javax.swing.JScrollPane();
            tblphieuxuatout = new javax.swing.JTable();
            jLabel5 = new javax.swing.JLabel();
            txtMaKM = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            lblTongcong = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            lblGiaKM = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));

            tblphieuxuatin.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Mã SP", "Tên SP", "Số lượng", "Giá bán"
                  }
            ));
            tblphieuxuatin.setRowHeight(50);
            jScrollPane2.setViewportView(tblphieuxuatin);

            btnthemsp.setBackground(new java.awt.Color(102, 204, 0));
            btnthemsp.setForeground(new java.awt.Color(255, 255, 255));
            btnthemsp.setText("Thêm");
            btnthemsp.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnthemspActionPerformed(evt);
                  }
            });

            jLabel12.setText("Nhân viên xuất");

            jLabel17.setText("Số lượng");

            txttennvxuat.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txttennvxuatActionPerformed(evt);
                  }
            });

            jLabel16.setText("Chọn mục");

            jLabel18.setText("Nhập tìm kiếm sản phẩm");

            txttimkiemsp.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txttimkiemspActionPerformed(evt);
                  }
            });
            txttimkiemsp.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txttimkiemspKeyReleased(evt);
                  }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(jLabel16)
                                          .addComponent(cbxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(txttimkiemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel18)))
                              .addComponent(txttennvxuat)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addComponent(jLabel17)
                                          .addComponent(jLabel12))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttennvxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttimkiemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addGap(22, 22, 22)
                                          .addComponent(cbxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
            );

            jPanel6.setBackground(new java.awt.Color(255, 255, 255));

            btnxuatphieu.setBackground(new java.awt.Color(102, 204, 0));
            btnxuatphieu.setForeground(new java.awt.Color(255, 255, 255));
            btnxuatphieu.setText("Xuất phiếu");
            btnxuatphieu.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnxuatphieuActionPerformed(evt);
                  }
            });

            jLabel13.setText("Họ tên KH");

            jLabel14.setText("Số ĐT");

            jLabel15.setText("Địa chỉ");

            combohoten.addItemListener(new java.awt.event.ItemListener() {
                  public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        combohotenItemStateChanged(evt);
                  }
            });

            tblphieuxuatout.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Mã SP", "Tên SP", "Số lượng", "Giá"
                  }
            ));
            tblphieuxuatout.setRowHeight(50);
            jScrollPane3.setViewportView(tblphieuxuatout);

            jLabel5.setText("Chương trình khuyến mãi áp dụng");

            txtMaKM.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtMaKMActionPerformed(evt);
                  }
            });

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel1.setText("Tổng cộng:");

            lblTongcong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 0, 0));
            jLabel2.setText("đ");

            jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel3.setText("Giá KM:");

            lblGiaKM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

            jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 0, 0));
            jLabel4.setText("đ");

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel13)
                                          .addComponent(jLabel15)
                                          .addComponent(combohoten, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel14)
                                          .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addComponent(txtdiachi)
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(0, 0, Short.MAX_VALUE))
                              .addComponent(txtMaKM)
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(btnxuatphieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                      .addComponent(jLabel1)
                                                      .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(lblTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(lblGiaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jLabel2)
                                                      .addComponent(jLabel4)))))
                              .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combohoten))
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel2)
                                          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addGap(6, 6, 6))))
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(lblTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblGiaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxuatphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
      }// </editor-fold>//GEN-END:initComponents

    private void combohotenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combohotenItemStateChanged
        // TODO add your handling code here:
        ArrayList<KhachHangDTO> listkh = khBUS.khDAO.selectAll();
        for (KhachHangDTO i : listkh) {
            if (("" + i.getHoten()).equalsIgnoreCase((String) combohoten.getSelectedItem())) {
                txtsdt.setText("" + i.getSdt());
                txtdiachi.setText("" + i.getDiachi());
            }
        }
    }//GEN-LAST:event_combohotenItemStateChanged

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblphieuxuatin.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm từ bảng 1.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu sản phẩm từ dòng được chọn
        Object[] rowData = new Object[4];
        for (int i = 0; i < 4; i++) {
            rowData[i] = tblphieuxuatin.getValueAt(selectedRow, i);
        }

        // Lấy số lượng nhập
        int soluong;
        try {
            soluong = Integer.parseInt(txtsoluong.getText().trim());
            if (soluong <= 0 || soluong > Integer.parseInt(rowData[2].toString())) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Trừ đi số lượng đã lấy
        tblphieuxuatin.setValueAt(Integer.parseInt(rowData[2].toString()) - soluong, selectedRow, 2);

        // Kiểm tra đã có sản phẩm ở bảng 2 chưa
        int check = 1;
        DefaultTableModel dt2 = (DefaultTableModel) tblphieuxuatout.getModel();
        for (int row = 0; row < dt2.getRowCount(); row++) {
            if (dt2.getValueAt(row, 0) == rowData[0]) {
                // Cộng thêm
                dt2.setValueAt(Integer.parseInt(dt2.getValueAt(row, 2).toString()) + soluong, row, 2);
                check = 0;
            }
        }
        if (check == 1) {
            // Thêm thông tin sản phẩm vào bảng 2
            rowData[2] = soluong; // Cập nhật số lượng
            dt2.addRow(rowData);
        }
        updateTotal();
        // Xóa số lượng đã nhập
        txtsoluong.setText("");
    }//GEN-LAST:event_btnthemspActionPerformed

    private void updateTotal() {
        DefaultTableModel model = (DefaultTableModel) tblphieuxuatout.getModel();
        int rowCount = model.getRowCount();
        int tongSL = 0;
        int tongGia = 0;
        for (int i = 0; i < rowCount; i++) {
            int sl = (int) model.getValueAt(i, 2);
            int gia = (int) model.getValueAt(i, 3);
            tongSL += sl;
            tongGia += sl * gia;
        }
        lblTongcong.setText(String.valueOf(tongGia));
        int giaKM = tongGia;
        ArrayList<KhuyenMaiDTO> listKM = new ArrayList<>();
        listKM = kmBUS.getAll();
        for (KhuyenMaiDTO km : listKM) {
            Date now = new Date();
            if (km.getLoaiKM().equals("Theo hóa đơn") && (!km.getTgBatDau().after(now) && !km.getTgKetThuc().before(now))) {
                ChiTietKMTheoHDDTO ctkm = new ChiTietKMTheoHDDTO();
                ctkm = ctkmHDBus.ctDao.getChiTietById(km.getMaKM());
                if (tongGia >= ctkm.getDkHoaDon()) {
                    txtMaKM.setText(km.getMaKM() + " - " + ctkm.getTenCTKM());
                    giaKM = tongGia - tongGia * ctkm.getPhanTramGiam() / 100;
                    break;
                }
            }
        }
        lblGiaKM.setText(String.valueOf(giaKM));

    }
    private void btnxuatphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatphieuActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) tblphieuxuatout.getModel();
            ArrayList<NhanVienDTO> listnv = nvBUS.getAll();
            ArrayList<KhachHangDTO> listkh = khBUS.getAll();
            ArrayList<LoHangDTO> listlh = lhBUS.getAll();

            int rowCount = model.getRowCount();
            Date thoigian = new Date(System.currentTimeMillis());
            java.sql.Date sqlDate = new java.sql.Date(thoigian.getTime());
            long tongtien = Long.parseLong(lblGiaKM.getText().trim());
            int sumsoluong = 0;
            int mapx = pxBUS.phieuXuatDAO.getAutoIncrement();

            String chTrKM = "";
            int maKM = 0;
            if (!txtMaKM.getText().trim().isEmpty()) {
                try {
                    chTrKM = txtMaKM.getText();
                    String[] parts = chTrKM.split(" - ");
                    maKM = Integer.parseInt(parts[0]);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Mã khuyến mãi không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            String tennv = txttennvxuat.getText().trim();
            int manv = listnv.stream().filter(nv -> tennv.equalsIgnoreCase(nv.getHoten()))
                    .findFirst().map(NhanVienDTO::getManv).orElse(1);

            String tenkh = combohoten.getSelectedItem().toString().trim();
            int makh = listkh.stream().filter(kh -> tenkh.equalsIgnoreCase(kh.getHoten()))
                    .findFirst().map(KhachHangDTO::getMaKH).orElse(1);

            PhieuXuatDTO pxAll = new PhieuXuatDTO(mapx, sqlDate, tongtien, sumsoluong, manv, makh);
            pxBUS.phieuXuatDAO.insert(pxAll);

            for (int i = 0; i < rowCount; i++) {
                int masp = Integer.parseInt(model.getValueAt(i, 0).toString());
                int soluong = Integer.parseInt(model.getValueAt(i, 2).toString());
                int dongia = Integer.parseInt(model.getValueAt(i, 3).toString());

                ChiTietPhieuXuatDTO ctpx = new ChiTietPhieuXuatDTO(mapx, masp, soluong, dongia);
                pxBUS.ctPhieuXuatDAO.insert(ctpx);

//            ArrayList<LoHangDTO> danhSachSanPham = new ArrayList<>();
//            for (LoHangDTO loHang : listlh) {
//                if (loHang.getMasp() == masp) {
//                    danhSachSanPham.add(loHang);
//                }
//            }
//            Collections.sort(danhSachSanPham, Comparator.comparing(LoHangDTO::getMaphieunhap));
//
//            for (LoHangDTO loHang : danhSachSanPham) {
//                if (soluong <= 0) break;
//                int soLuongHienTai = loHang.getSoluong();
//                if (soLuongHienTai > 0) {
//                    if (soLuongHienTai <= soluong) {
//                        soluong -= soLuongHienTai;
//                        loHang.setSoluong(0);
//                        lhBUS.lhDAO.updateQuantity(loHang.getMaphieunhap(), 0);
//                    } else {
//                        loHang.setSoluong(soLuongHienTai - soluong);
//                        lhBUS.lhDAO.updateQuantity(loHang.getMaphieunhap(), loHang.getSoluong());
//                        soluong = 0;
//                    }
//                }
//            }
//
//            if (soluong == 0) {
                boolean spUpdateSuccess = spBUS.subtractQuantity(masp, soluong);
                if (!spUpdateSuccess) {
                    JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
//            }
            }

            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Xuất hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            displaytoTable1(spBUS.spDAO.selectAll());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnxuatphieuActionPerformed

    private void txttennvxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttennvxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttennvxuatActionPerformed

    private void txtMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKMActionPerformed

      private void txttimkiemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemspActionPerformed
          // TODO add your handling code here:
      }//GEN-LAST:event_txttimkiemspActionPerformed

      private void txttimkiemspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemspKeyReleased
          // TODO add your handling code here:
          ArrayList<SanPhamDTO> result = new ArrayList<>();

          String text = txttimkiemsp.getText();
          String choose = (String) cbxAll.getSelectedItem();
          switch (choose) {
              case "Tất cả":
                  result = SearchSanPham.getInstance().searchTatCaSPPhieu(text);
                  break;
              case "Mã sản phẩm":
                  result = SearchSanPham.getInstance().searchMaSP(text);
                  break;
              case "Tên sản phẩm":
                  result = SearchSanPham.getInstance().searchTenSP(text);
                  break;
          }
          displaytoTable1(result);
      }//GEN-LAST:event_txttimkiemspKeyReleased

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnthemsp;
      private javax.swing.JButton btnxuatphieu;
      private javax.swing.JComboBox<String> cbxAll;
      private javax.swing.JComboBox<String> combohoten;
      private javax.swing.ButtonGroup groupGioiTinh;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel14;
      private javax.swing.JLabel jLabel15;
      private javax.swing.JLabel jLabel16;
      private javax.swing.JLabel jLabel17;
      private javax.swing.JLabel jLabel18;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JScrollPane jScrollPane3;
      private javax.swing.JLabel lblGiaKM;
      private javax.swing.JLabel lblTongcong;
      private javax.swing.JTable tblphieuxuatin;
      private javax.swing.JTable tblphieuxuatout;
      private javax.swing.JTextField txtMaKM;
      private javax.swing.JTextField txtdiachi;
      private javax.swing.JTextField txtsdt;
      private javax.swing.JTextField txtsoluong;
      private javax.swing.JTextField txttennvxuat;
      private javax.swing.JTextField txttimkiemsp;
      // End of variables declaration//GEN-END:variables
}
