package GUI.details;

import BUS.CTKMTheoSpBUS;
import BUS.SanPhamBUS;
import DAO.SanPhamDAO;
import DTO.ChiTietKMTheoHDDTO;
import DTO.ChiTietKMTheoSPDTO;
import DTO.KhuyenMaiDTO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class detailctkmtheosp extends javax.swing.JDialog {
    private ChiTietKMTheoSPDTO ctkmDTO=new ChiTietKMTheoSPDTO();
    ArrayList<ChiTietKMTheoSPDTO> list= new ArrayList<>();
    CTKMTheoSpBUS ctkmBUS= new CTKMTheoSpBUS();
    private DefaultTableModel model;
    /**
     * Creates new form detailctkmtheosp
     */
    public detailctkmtheosp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModal(modal);
        setLocationRelativeTo(null);
    }
    
    public detailctkmtheosp(javax.swing.JFrame owner, boolean modal, ChiTietKMTheoSPDTO ctkmDTO, int selectedMaKM) {
        super(owner, modal);
        this.ctkmDTO=ctkmDTO;
        initComponents();
        initTable();
        setModal(modal);
        setLocationRelativeTo(null);
        displayInfo();
        list = ctkmBUS.getAll();      
        loadDataToTable(list, selectedMaKM);    
        tblctsanpham.setDefaultEditor(Object.class, null);
}

    public final void initTable() {
        model = new DefaultTableModel();
        String[] headerTbl = new String[]{"STT", "Tên SP", "TG bắt đầu", "TG Kết thúc", "Phần trăm giảm"};
        model.setColumnIdentifiers(headerTbl);
        tblctsanpham.setModel(model);
        tblctsanpham.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblctsanpham.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblctsanpham.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblctsanpham.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblctsanpham.getColumnModel().getColumn(4).setPreferredWidth(30);
        
    }
    
    public final void loadDataToTable(ArrayList<ChiTietKMTheoSPDTO> ctkm, int selectedMaKm) {
        try {
            model.setRowCount(0); 
            int stt=1;
            for (ChiTietKMTheoSPDTO i : ctkm) { 
                if (i.getMaKM()==selectedMaKm){
                    SanPhamBUS spBus=new SanPhamBUS();   
                    String masp=i.getMaSP()+"";
                    System.out.println("mã sản phẩm: "+masp);
                    String tenSP=spBus.spDAO.selectById(masp).getTensp();
                    System.out.println("tên sản phẩm"+ tenSP);
                    model.addRow(new Object[]{
                        stt++, tenSP, i.getTgBatDau(), i.getTgKetThuc(),i.getPhanTramGiam()
                    });
                }
                
                
            }           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void displayInfo() {
    
    if (ctkmDTO!=null) {         
        txtMakm.setText(ctkmDTO.getMaKM()+"");       
        txtNVTao.setText(ctkmDTO.getNvTao());
        txtMakm.setEditable(false);
        txtNVTao.setEditable(false);
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin khuyến mãi", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMakm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNVTao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblctsanpham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtMakm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakmActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã khuyến mãi");

        jLabel3.setText("Chi tiết khuyến mãi");

        jLabel4.setText("Nhân viên tạo");

        txtNVTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNVTaoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(78, 158, 209));

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT KHUYẾN MÃI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        tblctsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "SL", "Thời gian BD", "Thời gian KT", "Phần trăm giảm"
            }
        ));
        tblctsanpham.setRowHeight(40);
        jScrollPane1.setViewportView(tblctsanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(239, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNVTao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNVTao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMakmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakmActionPerformed

    private void txtNVTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNVTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNVTaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailctkmtheosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailctkmtheosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailctkmtheosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailctkmtheosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                detailctkmtheosp dialog = new detailctkmtheosp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblctsanpham;
    private javax.swing.JTextField txtMakm;
    private javax.swing.JTextField txtNVTao;
    // End of variables declaration//GEN-END:variables
}
